import Head from "next/head";
import Sidebar from "@/components/sidebar/sidebar";
import Header from "@/components/header/header";
import Styles from "@/components/layout/layout.module.scss";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Smartlight</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/lotecicon.ico" />
      </Head>

      <div className="dashboard">
        {/* sidebar */}
        <Sidebar />
        {/* sidebar end */}

        {/* content */}
        <div className={`${Styles.content} layout_content`}>
          {/* header */}
          <Header />
          {/* main */}
          <main className={Styles.main}>
            <div className="container-fluid">{children}</div>
          </main>
        </div>
        {/* content end */}
      </div>
    </>
  );
}
